language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "lafeuille"

script:
  - ./mvnw org.owasp:dependency-check-maven:check
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
