language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: lafeuille

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && ./mvnw deploy -Pdocker -DskipTests
