language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "lafeuille"

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar