language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "lafeuille"

script:
  - ./mvnw clean org.openclover:clover-maven-plugin:setup package org.openclover:clover-maven-plugin:aggregate org.openclover:clover-maven-plugin:clover org.sonarsource.scanner.maven:sonar-maven-plugin:sonar